version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  commit-message:
      prefix: 'chore'
      include: 'scope'
  open-pull-requests-limit: 10