# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: GoSFFT

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.23

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Run examples
      run: |
        go run examples/fft1d/main.go
        go run examples/fft2d/main.go
        go run examples/fft3d/main.go
        go run cmd/gosfft-time-fft2/main.go
        go run cmd/gosfft-time-fft3/main.go
    - name: Cleanup
      run: |
        rm *.png
        rm *.bin
